# Generated by Django 4.1 on 2022-09-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_state_product_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="vendor",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="product",
            field=models.ManyToManyField(
                related_name="vendor_product", to="app.product"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipment_delivery_time",
            field=models.CharField(
                choices=[
                    ("1-3 Business Days", "1-3 days"),
                    ("1-5 Business Days", "1-5 days"),
                    ("1-15 Business Days", "1-15 days"),
                ],
                default="1-5 Business Days",
                max_length=20,
            ),
        ),
    ]
