# Generated by Django 4.1 on 2022-09-02 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_customuser_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField()),
                (
                    "currency",
                    models.CharField(
                        choices=[("$", "US Dollars ($)")], default="$", max_length=5
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sku", models.IntegerField()),
                ("image", models.URLField()),
                ("inventory", models.FloatField()),
                (
                    "state",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("shipment_delivery_time", models.CharField(max_length=50)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.vendor"
                    ),
                ),
            ],
        ),
    ]
