# Generated by Django 4.1 on 2022-09-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_vendor_product_product_vendor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("$", "US Dollar ($)")], default="$", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="static/images"),
        ),
    ]
