# Generated by Django 4.1 on 2022-09-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_customer_name_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="billing_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
