# Generated by Django 4.1 on 2022-09-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_customer_billing_address_alter_customer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="inventory", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product", name="sku", field=models.CharField(max_length=10),
        ),
    ]
