# Generated by Django 4.1 on 2022-09-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_product_currency_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_vendor",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_customer",
            field=models.BooleanField(default=True),
        ),
    ]
