# Generated by Django 4.1 on 2022-09-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_customuser_is_vendor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.URLField(),
        ),
    ]
