# Generated by Django 4.1 on 2022-09-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_product_inventory_alter_product_sku"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendor", old_name="title", new_name="company",
        ),
        migrations.RemoveField(model_name="customer", name="name",),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
